name: TNoodle

on:
  push:
    branches:
      master

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          git clone https://github.com/thewca/tnoodle.git ~/tnoodle && cd ~/tnoodle
          git checkout v0.15.0
          ./gradlew publishToMavenLocal
          cd -
          ./gradlew check
          ./gradlew :tnoodle-android:assemble
          ./gradlew :tnoodlejs-compiler:compileGwt
          mkdir tnoodle
          mv tnoodlejs-compiler/build/gwt/out/tnoodlejs tnoodle/js
          mv tnoodle-android/build/outputs/apk/ tnoodle/android

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:  
          publish_dir: tnoodle
          github_token: ${{ secrets.GITHUB_TOKEN }}